require('./lib/cat')


Cat.create({:name => "Tbone", :wins => 0, :loss => 0, :image => "http://s18.postimg.org/x9s3ehc09/tbone.jpg", :bio => "Tbone has the crouch of a lackey. He was brought up to be independent and after leaving school he fell in with a bad crowd. He married badly. When he served time for fraud he took up painting. Now he travel round in a beaten up old Ford van."})
Cat.create({:name => "Freckles", :wins => 0, :loss => 0, :image => "http://s8.postimg.org/rhzsiqluc/freckles.jpg", :bio => "Freckles has a knowing look. Her parents were military personnel. She was brought up on the wrong side of the tracks and bought a boat. She has an oafish air. She found love through internet dating. Now she is plotting revenge on her old enemies." })
Cat.create({:name => "Truman", :wins => 0, :loss => 0, :image => "http://s11.postimg.org/k9osn032b/truman.jpg", :bio => "Truman has a winning smile. The people he lived with were animals. He was brought up in a quiet suburb and started up an internet venture. He has sneering disdain for everyone. He found love through internet dating. Now he has a permanent tan."})
Cat.create({:name => "Cheester", :wins => 0, :loss => 0, :image => "http://s21.postimg.org/5zh0tn63r/Cheester.jpg", :bio => "Cheester is bright and breezy. He has a lazy attitude. He was brought up by a single mother. When he graduated from junior college, he worked as an artist's model. He married the first person who asked him. When his partner died he had a nervous breakdown."})
Cat.create({:name => "Bob", :wins => 0, :loss => 0, :image => "http://s12.postimg.org/b87ykosi5/Bob.jpg", :bio => "Bob is bright and breezy. He has the classic good looks of a film star. He was a runaway. His parents were kind but misguided. He was educated by a mail order company based in Luxembourg. He married the girl next door. He has a criminal record."})
Cat.create({:name => "Garfield", :wins => 0, :loss => 0, :image => "http://s11.postimg.org/gd8pirog3/Garfield.jpg", :bio => "Garfield is an abrupt and brusque personality. She has a ravaged face. She was educated by overhearing adult conversations. She was constantly in trouble as a child for causing mischief. Her parents were academics. After she got expelled from school she had a kid. Now she eats nothing but fast food."})
Cat.create({:name => "Mr.Yam Yam", :wins => 0, :loss => 0, :image => "http://s12.postimg.org/bu1iujcy5/Mr_Yam_Yam.jpg", :bio => "Mr. Yam Yam has the smooth features of an innocent. He was brought up by a single mother and after leaving school he joined a gang. He never married. When disaster struck he turned to amateur sleuthing. Now he spends his time harping back to the good old days."})
Cat.create({:name => "Spanky", :wins => 0, :loss => 0, :image => "http://s24.postimg.org/vybqqlxs5/Spanky.jpg", :bio => "Spanky has the strutting pose of a model. Her parents were restaurant owners. She was brought up on the wrong side of the tracks and broke her leg in a skiing accident. She has an aloofness. She found love through internet dating. Now she's writing their memoirs."})
Cat.create({:name => "Bruce", :wins => 0, :loss => 0, :image => "http://s9.postimg.org/5jtrj5b73/Bruce.jpg", :bio => "Bruce has a knowing look. He were brought up as a science experiment and after leaving school he joined the police. He never married. When insurgents staged a coup he took up painting. Now he visits the shrink once a week."})
Cat.create({:name => "Shiba", :wins => 0, :loss => 0, :image => "http://s22.postimg.org/5pyyi112p/Shiba.jpg", :bio => "Shiba is a mess of emotions. She has no moral fibre. She was brought up in the inner-city. When she left to seek her fortune she did voluntary service in Africa. She married her flatmate. When disaster struck she became advisor to a rich Arabian prince."})
Cat.create({:name => "Buster", :wins => 0, :loss => 0, :image => "http://s22.postimg.org/5pyyi112p/Shiba.jpg", :bio => "Buster is gloomy and sad. He has a history of cheating on his partners. He was brought up the son of a diplomat. When he got expelled from school he spent a few years as a tour guide. He married the girl next door. When he was exposed by the press he found himself unable to continue."})
